/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test.StudentModel;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;

/**
 *
 * @author edz
 */
public class Add extends javax.swing.JFrame {
//    public int j=0;
//    public  static JRadioButton [] jp=new JRadioButton[20];
//    public  static String [] result =new String[20];
//    public static int number=0;
//    public static String [][] charu=new String [20][10];
//    /**
//     * Creates new form student
//     */
//    public Add() throws IOException {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private  void initComponents() throws IOException {
//        jButton5 = new javax.swing.JButton();
//        jTextField1 = new javax.swing.JTextField();
//        jButton7 = new javax.swing.JButton();
//        jRadioButton1 = new javax.swing.JRadioButton();
//        jRadioButton2 = new javax.swing.JRadioButton();
//        jRadioButton3 = new javax.swing.JRadioButton();
//        jRadioButton4 = new javax.swing.JRadioButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTextArea1 = new javax.swing.JTextArea();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        jTextArea2 = new javax.swing.JTextArea();
//        jScrollPane3 = new javax.swing.JScrollPane();
//        jTextArea3 = new javax.swing.JTextArea();
//        jScrollPane4 = new javax.swing.JScrollPane();
//        jTextArea4 = new javax.swing.JTextArea();
//        jScrollPane5 = new javax.swing.JScrollPane();
//        jTextArea5 = new javax.swing.JTextArea();
//
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("学生系统");
//        ButtonGroup buttonGroup=new ButtonGroup();
//        jButton5.setText("保存");
//
//        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
//        jTextField1.setText("   题 目 添 加 系 统");
//        jTextField1.setActionCommand("<Not Set>");
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            @Override
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//        jButton7.setText("提交");
//        jButton7.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                 String pl="";
//                 for(int i=0;i<number;i++){
//                     pl+=charu[i][0]+"@"+charu[i][1]+"@"+charu[i][2]+"@"+charu[i][3]+"@"+charu[i][4]+"@"+result[i]+"#";
//
//                 }
//                Socket socket = Sockett.socket;
//                OutputStream outputStream = null;
//                try {
//                    outputStream = socket.getOutputStream();
//                } catch (IOException ex) {
//                    ex.printStackTrace();
//                }
//                try {
//                    outputStream.write(pl.getBytes());
//                    outputStream.flush();
//                } catch (IOException ex) {
//                    ex.printStackTrace();
//                }
//                dispose();
//
//                new AdmMenu().setVisible(true);
//            }
//        });
//        jRadioButton1.setText("A");
//        jRadioButton2.setText("B");
//        jRadioButton3.setText("C");
//        jRadioButton4.setText("D");
//        buttonGroup.add(jRadioButton1);
//        buttonGroup.add(jRadioButton2);
//        buttonGroup.add(jRadioButton3);
//        buttonGroup.add(jRadioButton4);
//        jButton5.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                    charu[number][0]=jTextArea1.getText();
//                    charu[number][1]=jTextArea2.getText();
//                    charu[number][2]=jTextArea3.getText();
//                    charu[number][3]=jTextArea4.getText();
//                    charu[number][4]=jTextArea5.getText();
//                    number++;
//                jTextArea1.setText("");
//                jTextArea2.setText("");
//                jTextArea3.setText("");
//                jTextArea4.setText("");
//                jTextArea5.setText("");
//                buttonGroup.clearSelection();
//            }
//        });
//        jRadioButton1.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                result[number]=jRadioButton1.getText();
//            }
//        });
//        jRadioButton2.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                result[number]=jRadioButton2.getText();
//            }
//        });
//        jRadioButton3.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//
//                result[number]=jRadioButton3.getText();
//            }
//        });
//        jRadioButton4.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                System.out.println("number"+number);
//                result[number]=jRadioButton4.getText();
//            }
//        });
//        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
//        jScrollPane1.setViewportView(jTextArea1);
//
//        jTextArea2.setColumns(20);
//        jTextArea2.setRows(5);
//        jScrollPane2.setViewportView(jTextArea2);
//
//        jTextArea3.setColumns(20);
//        jTextArea3.setRows(5);
//        jScrollPane3.setViewportView(jTextArea3);
//
//        jTextArea4.setColumns(20);
//        jTextArea4.setRows(5);
//        jScrollPane4.setViewportView(jTextArea4);
//
//        jTextArea5.setColumns(20);
//        jTextArea5.setRows(5);
//        jScrollPane5.setViewportView(jTextArea5);
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jButton5)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addComponent(jButton7)
//                                                .addGap(9, 9, 9))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(80, 80, 80)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                                        .addComponent(jRadioButton2)
//                                                        .addComponent(jRadioButton3)
//                                                        .addComponent(jRadioButton4))
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addGap(0, 0, Short.MAX_VALUE))
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                                        .addComponent(jScrollPane3)
//                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
//                                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)))))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(83, 83, 83)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jScrollPane1)
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jRadioButton1)
//                                                                .addGap(4, 4, 4)
//                                                                .addComponent(jScrollPane2)))))
//                                .addContainerGap())
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(40, 40, 40)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                .addGap(21, 21, 21)
//                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(10, 10, 10)
//                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jRadioButton1)
//                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jRadioButton2)
//                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jRadioButton3)
//                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jRadioButton4)
//                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                .addGap(16, 16, 16)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton5)
//                                        .addComponent(jButton7))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    // Variables declaration - do not modify
//    private javax.swing.JButton jButton5;
//    private javax.swing.JButton jButton7;
//    public static javax.swing.JRadioButton jRadioButton1;
//    public  static javax.swing.JRadioButton jRadioButton2;
//    public static javax.swing.JRadioButton jRadioButton3;
//    public  static javax.swing.JRadioButton jRadioButton4;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JScrollPane jScrollPane3;
//    private javax.swing.JScrollPane jScrollPane4;
//    private javax.swing.JScrollPane jScrollPane5;
//    public static javax.swing.JTextArea jTextArea1;
//    public static javax.swing.JTextArea jTextArea2;
//    public static javax.swing.JTextArea jTextArea3;
//    public static javax.swing.JTextArea jTextArea4;
//    public  static javax.swing.JTextArea jTextArea5;
//    private javax.swing.JTextField jTextField1;
//    // End of variables declaration
}
