/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test.StudentModel;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;

/**
 *
 * @author edz
 */
public class StuTest extends javax.swing.JFrame {
    public int j;
   public  static JRadioButton [] jp;
    public static String [] tem;
    public  static String [] result;
    public static int number=0;
    /**
     * Creates new form student
     */
    public StuTest() throws IOException {
        jp=new JRadioButton[20];
        result =new String[20];
        number=0;
       initComponents();
    }
    public  void  close(){
      JOptionPane.showMessageDialog(null,"提交","",JOptionPane.INFORMATION_MESSAGE);
      String pll="";
        for(int i=0;i<20;i++){
            if(result[i]==null){
                pll+="R";
            }else  pll+=result[i];
        }
        OutputStream outputStream=null;
        try {
            outputStream=Sockett.socket.getOutputStream();
            outputStream.write(pll.getBytes());
            outputStream.flush();
            dispose();
            new Student().setVisible(true);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void listen(){
        while (true){
            jButton5.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {

                }
            });
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private  void initComponents() throws IOException {
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        Socket sockett= Sockett.socket;
        InputStream i=sockett.getInputStream();
        InputStreamReader io=new InputStreamReader(i);
        String pl="";
        int y=0;
        char [] bytes=new char[100];
        while ((y=io.read(bytes))!=-1){
            pl+=new String(bytes,0,y);
            if(y!=100){
                break;
            }
        }
        pl+=new String(bytes,0,y);

        tem=pl.split("#");
        String [] pll=tem[0].split("@");
        jTextArea1.setText(1+","+pll[0]);
        jTextArea2.setText(pll[1]);
        jTextArea3.setText(pll[2]);
        jTextArea4.setText(pll[3]);
        jTextArea5.setText(pll[4]);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("学生系统");
        ButtonGroup buttonGroup=new ButtonGroup();
        jButton5.setText("下一题");

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        jTextField1.setText("半圆学生考试系统");

        jTextField1.setActionCommand("<Not Set>");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jButton7.setText("提交");
        jButton7.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String pl="";
                for(int i=0;i<20;i++){
                    if(result[i]==null){
                        pl+="第"+(i+1)+"题没做，";
                    }
                }

                int isDelete = JOptionPane.showConfirmDialog(null, pl, "提示", JOptionPane.YES_NO_CANCEL_OPTION);
                String pll="";
                    if(isDelete==JOptionPane.YES_OPTION){
                        for(int i=0;i<20;i++){
                            if(result[i]==null){
                                pll+="R";
                            }else  pll+=result[i];
                        }
                        OutputStream outputStream=null;
                        try {
                            outputStream=Sockett.socket.getOutputStream();
                            outputStream.write(pll.getBytes());
                            outputStream.flush();
                            dispose();
                            new Student().setVisible(true);
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                    }

            }
        });
        jRadioButton1.setText("A");

        jRadioButton2.setText("B");

        jRadioButton3.setText("C");

        jRadioButton4.setText("D");

        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
        buttonGroup.add(jRadioButton3);
        buttonGroup.add(jRadioButton4);
        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(number);
                if(number<19) {
                    String[] pll = tem[++number].split("@");
                    if(result[number]!=null){
                        if(result[number].equals("A")){
                            jRadioButton1.setSelected(true);
                        }else if(result[number].equals("B")){
                            jRadioButton2.setSelected(true);
                        }else if (result[number].equals("C")){
                            jRadioButton3.setSelected(true);
                        }else jRadioButton4.setSelected(true);
                    }
                    else{
                       buttonGroup.clearSelection();
                    }
                    jTextArea1.setText(number+1+","+pll[0]);
                    jTextArea2.setText(pll[1]);
                    jTextArea3.setText(pll[2]);
                    jTextArea4.setText(pll[3]);
                    jTextArea5.setText(pll[4]);
                }
                else{
                    JOptionPane.showMessageDialog(null, "已经是最后一页","提示",JOptionPane.INFORMATION_MESSAGE);

                }
            }
        });
        jRadioButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("number"+number);
                result[number]=jRadioButton1.getText();
            }
        });
        jRadioButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("number"+number);
                result[number]=jRadioButton2.getText();
            }
        });
        jRadioButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                result[number]=jRadioButton3.getText();
            }
        });
        jRadioButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("number"+number);
                result[number]=jRadioButton4.getText();
            }
        });
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jRadioButton5.setText("1");

        jRadioButton6.setText("2");

        jRadioButton7.setText("3");

        jRadioButton8.setText("4");

        jRadioButton9.setText("7");

        jRadioButton10.setText("8");

        jRadioButton11.setText("5");

        jRadioButton12.setText("6");

        jRadioButton13.setText("11");

        jRadioButton14.setText("12");

        jRadioButton15.setText("13");

        jRadioButton16.setText("14");

        jRadioButton17.setText("15");

        jRadioButton18.setText("16");

        jRadioButton19.setText("17");

        jRadioButton20.setText("18");

        jRadioButton21.setText("9");

        jRadioButton22.setText("10");

        jRadioButton25.setText("19");

        jRadioButton26.setText("20");

        jp[0]=jRadioButton5;
        jp[1]=jRadioButton6;
        jp[2]=jRadioButton7;
        jp[3]=jRadioButton8;
        jp[4]=jRadioButton9;
        jp[5]=jRadioButton10;
        jp[6]=jRadioButton11;
        jp[7]=jRadioButton12;
        jp[8]=jRadioButton13;
        jp[9]=jRadioButton14;
        jp[10]=jRadioButton15;
        jp[11]=jRadioButton16;
        jp[12]=jRadioButton17;
        jp[13]=jRadioButton18;
        jp[14]=jRadioButton19;
        jp[15]=jRadioButton20;
        jp[16]=jRadioButton21;
        jp[17]=jRadioButton22;
        jp[18]=jRadioButton25;
        jp[19]=jRadioButton26;
        ButtonGroup buttonGroup1=new ButtonGroup();
        for(int j=0;j<20;j++){
            buttonGroup1.add(jp[j]);
        }
 for(j=0;j<20;j++) {
     Llist llist=new Llist();
     llist.setX(jp[j]);
     llist.setButtonGroup(buttonGroup);
     jp[j].addActionListener(llist);
 }
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton7)
                                                .addGap(9, 9, 9))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jRadioButton2)
                                                        .addComponent(jRadioButton3)
                                                        .addComponent(jRadioButton4))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane3)
                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jRadioButton1)
                                                                .addGap(4, 4, 4)
                                                                .addComponent(jScrollPane2)))))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton13)
                                                .addGap(6, 6, 6)
                                                .addComponent(jRadioButton14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton20))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton5)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton6)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton7)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton8)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton11)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton12)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton9)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton10)))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton26))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton21)
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButton22)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton4)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jRadioButton5)
                                                        .addComponent(jRadioButton6)
                                                        .addComponent(jRadioButton7)
                                                        .addComponent(jRadioButton8)
                                                        .addComponent(jRadioButton11)
                                                        .addComponent(jRadioButton12)
                                                        .addComponent(jRadioButton9)
                                                        .addComponent(jRadioButton10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jRadioButton13)
                                                        .addComponent(jRadioButton14)
                                                        .addComponent(jRadioButton15)
                                                        .addComponent(jRadioButton16)
                                                        .addComponent(jRadioButton17)
                                                        .addComponent(jRadioButton18)
                                                        .addComponent(jRadioButton19)
                                                        .addComponent(jRadioButton20)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jRadioButton21)
                                                        .addComponent(jRadioButton22))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jRadioButton25)
                                                        .addComponent(jRadioButton26))))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton5)
                                        .addComponent(jButton7))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    public static javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
   public  static javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
   public static javax.swing.JRadioButton jRadioButton3;
    public  static javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextArea jTextArea3;
   public static javax.swing.JTextArea jTextArea4;
    public  static javax.swing.JTextArea jTextArea5;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration
}
